name: Deploy GKE

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/109344998901/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "terraform-sa@application-prod-497803.iam.gserviceaccount.com"

      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init

      - name: Terraform Apply
        working-directory: environments/dev
        run: terraform apply -auto-approve
