name: Deploy App to GKE

on:
  workflow_dispatch:

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      USE_GKE_GCLOUD_AUTH_PLUGIN: "True"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/109344998901/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "terraform-sa@application-prod-497803.iam.gserviceaccount.com"

      - name: Setup gcloud with GKE auth plugin
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: "gke-gcloud-auth-plugin,kubectl"

      - name: Check tools
        run: |
          gcloud version
          kubectl version --client
          gke-gcloud-auth-plugin --version

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials dev-gke-cluster \
            --zone asia-southeast1-a \
            --project application-prod-497803

      - name: Deploy Kubernetes manifests
        run: kubectl apply -f k8s/proxy/

      - name: Show resources
        run: |
          kubectl get pods
          kubectl get svc
          kubectl get ingress
